# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
inhibit_all_warnings!

workspace '../SkyEng.xcworkspace'

def di
  pod 'Swinject', '~> 2.7.1'
end 

def ui
  
end

def network
  pod "Alamofire", '~> 5.1'
end


def pods
  ui
  di
  network
end

def ui_components_sdk
  podspec :path => '../UIComponentsSDK/UIComponentsSDK.podspec'
end

def network_sdk
  podspec :path => '../NetworkSDK/NetworkSDK.podspec'
end

target 'SkyEng' do
  use_frameworks!
  pods
end

target 'UIComponentsSDK' do
  project '../UIComponentsSDK/UIComponentsSDK.xcodeproj'
  ui_components_sdk
end

target 'NetworkSDK' do
  project '../NetworkSDK/NetworkSDK.xcodeproj'
  network_sdk
end
