# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
inhibit_all_warnings!

workspace '../SkyEng.xcworkspace'

def script
  pod 'SwiftLint', '~> 0.43.1'
end

def di
  pod 'Swinject', '~> 2.7.1'
end 

def ui
  pod 'SnapKit', '~> 5.0.0'
end

def reacive
  pod 'ReactiveSwift', '~> 6.1'
  pod 'ReactiveCocoa', '~> 11.2'
end

def network
  pod "Alamofire", '~> 5.1'
end

def pods
  script
  ui
  di
  reacive
  network
end

def ui_components_sdk
  podspec :path => '../UIComponentsSDK/UIComponentsSDK.podspec'
end

def network_sdk
  podspec :path => '../NetworkSDK/NetworkSDK.podspec'
end

target 'SkyEng' do
  use_frameworks!
  pods
end

target 'UIComponentsSDK' do
  project '../UIComponentsSDK/UIComponentsSDK.xcodeproj'
  ui_components_sdk
end

target 'NetworkSDK' do
  project '../NetworkSDK/NetworkSDK.xcodeproj'
  network_sdk
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
